version: '3'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: new_user
      POSTGRES_PASSWORD: new_password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U new_user -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: .
    environment:
      PG_CONNECTION_STRING: "host=postgres dbname=mydatabase user=new_user password=new_password sslmode=disable"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started